name: Rust
           

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
                - name: cargo-install
                  uses: baptiste0928/cargo-install@v3.0.1

                - name: install-skyline
                  run: cargo install cargo-skyline
                  
                - name: build-nro
                  run: cargo skyline build
