name: Rust
            

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: jam1garner/cargo-skyline@v3.2.0
    - uses: actions/checkout@v3
    - name: Build
      run: cargo skyline build
