name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
                - name: Install cargo-skyline
                  run: cargo install cargo-skyline
                  
                - name: Build libcrmod.nro
                  run: cargo skyline build --release
                  
                - name: Upload libcrmod.nro
                  uses: actions/upload-artifact@v4
                  with:
                    name: main-nro
                    path: target/aarch64-skyline-switch/release/libcrmod.nro
